#!/command/with-contenv bash

groupmod -o -g "${PGID}" abc
usermod -o -u "${PUID}" abc

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

if test $(find /app \( ! -user abc -o ! -group abc \) | wc -c) -ne 0; then
    echo "Applying PUID and PGID to /app, takes a sec"
    chown -R abc:abc /app
fi

if test $(find /config \( ! -user abc -o ! -group abc \) | wc -c) -ne 0; then
    echo "Applying PUID and PGID to /config, takes a sec"
    chown -R abc:abc /config
fi

if test $(find /var/lib/nginx \( ! -user abc -o ! -group abc \) | wc -c) -ne 0; then
    echo "Applying PUID and PGID to /var/lib/nginx, takes a sec"
    chown -R abc:abc /var/lib/nginx
fi

if test $(find /var/log/nginx \( ! -user abc -o ! -group abc \) | wc -c) -ne 0; then
    echo "Applying PUID and PGID to /var/log/nginx, takes a sec"
    chown -R abc:abc /var/log/nginx
fi

chmod o+w /dev/stderr
chmod o+w /dev/stdout

echo "Permissions all set up"
