#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID}
PGID=${PGID}

addgroup -g "$PGID" -S abc
adduser -u "$PUID" -S abc -G abc

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

echo "Applying PUID and PGID to app, takes a sec"
chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /var/lib/nginx
chown -R abc:abc /var/log/nginx

chmod o+w /dev/stderr
chmod o+w /dev/stdout
