#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ ! -f "/config/app.key" ]; then
    echo "App key does not exist, creating"
    php -r 'echo "base64:" . base64_encode(random_bytes(32));' > /config/app.key
    chown abc:abc /config/app.key
fi
