#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "Migrating database"
echo "-------------------------------------"
if [ ! -f "/config/database.sqlite" ]; then
    echo "/config/database.sqlite does not exist, creating"
    s6-setuidgid abc touch /config/database.sqlite
fi
s6-setuidgid abc php /app/artisan migrate --force
