#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "Optimizing code"
echo "-------------------------------------"
s6-setuidgid abc php /app/artisan config:cache
s6-setuidgid abc php /app/artisan route:cache
s6-setuidgid abc php /app/artisan view:cache
